# Generated by Django 4.0.8 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rename_private_key_bot_address_alter_bot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
