# Generated by Django 4.1 on 2022-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_poolcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcontract',
            name='abi',
            field=models.TextField(default='', max_length=255),
        ),
    ]
