# Generated by Django 4.1 on 2022-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_token_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='contract',
            new_name='uniswap_contract',
        ),
        migrations.AddField(
            model_name='token',
            name='uniswap_abi',
            field=models.CharField(default='', max_length=255),
        ),
    ]
