# Generated by Django 4.1 on 2022-09-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
