# Generated by Django 4.1 on 2022-09-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_transaction_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uniswap_abi',
            field=models.TextField(default='', max_length=255),
        ),
    ]
