# Generated by Django 4.1 on 2022-09-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_alter_token_uniswap_abi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uniswap_abi',
            field=models.TextField(default=''),
        ),
    ]
