# Generated by Django 4.1 on 2022-10-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_alter_token_uniswap_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pair',
            field=models.CharField(default='', max_length=255),
        ),
    ]
