# Generated by Django 4.1 on 2022-10-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0016_targetwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetwallet',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
