# Generated by Django 4.0.8 on 2022-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0019_alter_poolcontract_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcontract',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
