# Generated by Django 4.0.8 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0020_poolcontract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'ethereum'), ('polygon', 'polygon'), ('bsc', 'bsc'), ('avalanche', 'avalanche'), ('solana', 'solana')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='pair',
            field=models.CharField(choices=[('usdt', 'usdt'), ('usdc', 'usdc'), ('eth', 'eth'), ('bnb', 'bnb'), ('busd', 'busd'), ('avax', 'avax'), ('matic', 'matic')], default='', max_length=255),
        ),
    ]
