# Generated by Django 4.0.8 on 2022-10-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0021_alter_token_chain_alter_token_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='chain',
            field=models.CharField(choices=[('', ''), ('ethereum', 'ethereum'), ('arbitrum', 'arbitrum'), ('polygon', 'polygon'), ('bsc', 'bsc'), ('avalanche', 'avalanche'), ('solana', 'solana')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='pair',
            field=models.CharField(choices=[('', ''), ('usdt', 'usdt'), ('usdc', 'usdc'), ('eth', 'eth'), ('bnb', 'bnb'), ('busd', 'busd'), ('avax', 'avax'), ('matic', 'matic'), ('dai', 'dai')], default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PairContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex', models.CharField(default='', max_length=25)),
                ('contract', models.CharField(default='', max_length=255)),
                ('abi', models.TextField(default='')),
                ('pair', models.CharField(choices=[('', ''), ('usdt', 'usdt'), ('usdc', 'usdc'), ('eth', 'eth'), ('bnb', 'bnb'), ('busd', 'busd'), ('avax', 'avax'), ('matic', 'matic'), ('dai', 'dai')], default='', max_length=15)),
                ('chain', models.CharField(choices=[('', ''), ('ethereum', 'ethereum'), ('arbitrum', 'arbitrum'), ('polygon', 'polygon'), ('bsc', 'bsc'), ('avalanche', 'avalanche'), ('solana', 'solana')], default='', max_length=255)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.token')),
            ],
        ),
    ]
