# Generated by Django 4.0.8 on 2022-10-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0022_alter_token_chain_alter_token_pair_paircontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paircontract',
            old_name='contract',
            new_name='contract_address',
        ),
    ]
