# Generated by Django 4.0.8 on 2022-10-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0023_rename_contract_paircontract_contract_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='token',
            name='uniswap_abi',
        ),
        migrations.RemoveField(
            model_name='token',
            name='uniswap_contract',
        ),
    ]
